project_id = "qeqfbywgcokyxvubjlhy"

[functions.calm-magic-assistant]
verify_jwt = false

[functions.compass-prompt]
verify_jwt = false

[functions.create-prd]
verify_jwt = true

[functions.custom-agent]
verify_jwt = false

[functions.generate-prd-stage]
verify_jwt = true

[functions.tile-agent]
verify_jwt = false
