// PRD Export utilities for markdown and PDF export

interface PrdData {
  id: string;
  title: string;
  status: string;
  prototype_stage: string;
  created_at: string;
  updated_at: string;
  // Dominant patterns
  main_dimension?: string | null;
  main_quadrant?: string | null;
  main_senge_focus?: string | null;
  main_board?: string | null;
  main_oscillation?: string | null;
  // POLLEN layer
  love_signals_summary?: string | null;
  love_decision_to_exist?: string | null;
  // NOEM layer
  magic_storyworld?: string | null;
  magic_prd_outline?: string | null;
  magic_hypotheses?: string | null;
  magic_patterns?: string | null;
  // POEM layer
  calm_requirements?: string | null;
  calm_risks_and_limits?: string | null;
  // TOTEM layer
  open_ontology_and_graph?: string | null;
  open_real_workflow?: string | null;
  open_adjustment_plan?: string | null;
  // ANTHEM layer (execution)
  free_first_poem_description?: string | null;
  free_totem_anthem?: string | null;
  free_success_criteria?: string | null;
  free_next_cycle_hooks?: string | null;
}

const STAGE_LABELS: Record<string, string> = {
  'A_POIETIC': 'A — Poietic',
  'B_DIEGETIC': 'B — Diegetic',
  'C_OPERATIONAL': 'C — Operational',
  'D_MVP': 'D — MVP',
};

const formatFieldLabel = (field: string): string => {
  return field
    .replace(/^(love_|magic_|calm_|open_|free_)/, '')
    .replace(/_/g, ' ')
    .replace(/^\w/, c => c.toUpperCase());
};

const formatContent = (content: string | null | undefined): string => {
  if (!content || !content.trim()) return '_No content yet_';
  return content.trim();
};

export const generatePrdMarkdown = (prd: PrdData): string => {
  const date = new Date(prd.updated_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const stageLabel = STAGE_LABELS[prd.prototype_stage] || prd.prototype_stage;

  let md = `# ${prd.title}

**Status:** ${prd.status.charAt(0).toUpperCase() + prd.status.slice(1)}  
**Stage:** ${stageLabel}  
**Last Updated:** ${date}

`;

  // Dominant Patterns
  const patterns: string[] = [];
  if (prd.main_dimension) patterns.push(`Dimension: ${prd.main_dimension}`);
  if (prd.main_quadrant) patterns.push(`Quadrant: ${prd.main_quadrant}`);
  if (prd.main_senge_focus) patterns.push(`Senge Focus: ${prd.main_senge_focus}`);
  if (prd.main_board) patterns.push(`Board: ${prd.main_board}`);
  if (prd.main_oscillation) patterns.push(`Oscillation: ${prd.main_oscillation}`);

  if (patterns.length > 0) {
    md += `## Dominant Patterns

${patterns.map(p => `- ${p}`).join('\n')}

---

`;
  }

  // POLLEN Layer
  md += `## 🌱 POLLEN — Raw Signals & Context

### Signals Summary
${formatContent(prd.love_signals_summary)}

### Decision to Exist
${formatContent(prd.love_decision_to_exist)}

---

`;

  // NOEM Layer
  md += `## 💎 NOEM — Conceptual Atoms

### Storyworld
${formatContent(prd.magic_storyworld)}

### PRD Outline
${formatContent(prd.magic_prd_outline)}

### Hypotheses
${formatContent(prd.magic_hypotheses)}

### Patterns
${formatContent(prd.magic_patterns)}

---

`;

  // POEM Layer
  md += `## 📖 POEM — Narrative Structures

### Requirements
${formatContent(prd.calm_requirements)}

### Risks & Limits
${formatContent(prd.calm_risks_and_limits)}

---

`;

  // TOTEM Layer
  md += `## 🏛️ TOTEM — Semantic Forms

### Ontology & Graph
${formatContent(prd.open_ontology_and_graph)}

### Real Workflow
${formatContent(prd.open_real_workflow)}

### Adjustment Plan
${formatContent(prd.open_adjustment_plan)}

---

`;

  // ANTHEM Layer (Execution)
  md += `## 🎵 ANTHEM — Integration & Execution

### First Poem Description
${formatContent(prd.free_first_poem_description)}

### Totem Anthem
${formatContent(prd.free_totem_anthem)}

### Success Criteria
${formatContent(prd.free_success_criteria)}

### Next Cycle Hooks
${formatContent(prd.free_next_cycle_hooks)}

---

_Generated by Calm Magic Board_
`;

  return md;
};

export const downloadMarkdown = (prd: PrdData): void => {
  const markdown = generatePrdMarkdown(prd);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const filename = `${prd.title.toLowerCase().replace(/\s+/g, '-')}-prd.md`;
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportPrdAsPdf = (prd: PrdData): void => {
  const markdown = generatePrdMarkdown(prd);
  
  // Convert markdown to simple HTML for print
  const html = markdownToHtml(markdown);
  
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export as PDF');
    return;
  }

  printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <title>${prd.title} - PRD</title>
  <style>
    @media print {
      body { margin: 0.5in; }
      h1 { page-break-after: avoid; }
      h2 { page-break-after: avoid; }
      h3 { page-break-after: avoid; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem;
      color: #1a1a1a;
    }
    h1 {
      font-size: 2rem;
      border-bottom: 2px solid #e5e5e5;
      padding-bottom: 0.5rem;
      margin-bottom: 1rem;
    }
    h2 {
      font-size: 1.5rem;
      color: #333;
      margin-top: 2rem;
      border-bottom: 1px solid #eee;
      padding-bottom: 0.25rem;
    }
    h3 {
      font-size: 1.1rem;
      color: #555;
      margin-top: 1.5rem;
    }
    p {
      margin: 0.75rem 0;
    }
    ul {
      padding-left: 1.5rem;
    }
    li {
      margin: 0.25rem 0;
    }
    hr {
      border: none;
      border-top: 1px solid #e5e5e5;
      margin: 2rem 0;
    }
    em {
      color: #888;
    }
    .meta {
      color: #666;
      font-size: 0.9rem;
    }
  </style>
</head>
<body>
  ${html}
  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 250);
    };
  </script>
</body>
</html>
  `);
  
  printWindow.document.close();
};

// Simple markdown to HTML converter
const markdownToHtml = (md: string): string => {
  return md
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/_(.+?)_/g, '<em>$1</em>')
    // Lists
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // Line breaks to paragraphs
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(.+)$/gm, (match) => {
      if (match.startsWith('<')) return match;
      return `<p>${match}</p>`;
    })
    // Clean up empty paragraphs
    .replace(/<p><\/p>/g, '')
    .replace(/<p>(<h[123]>)/g, '$1')
    .replace(/(<\/h[123]>)<\/p>/g, '$1')
    .replace(/<p>(<ul>)/g, '$1')
    .replace(/(<\/ul>)<\/p>/g, '$1')
    .replace(/<p>(<hr>)<\/p>/g, '$1');
};
