-- First, nullify tile references in polen_entries to avoid FK constraint violations
UPDATE polen_entries SET tile_id = NULL WHERE tile_id IS NOT NULL;

-- Also nullify references in journal_cycles
UPDATE journal_cycles SET current_tile_id = NULL WHERE current_tile_id IS NOT NULL;

-- Also nullify references in tolerance_expansion_events
UPDATE tolerance_expansion_events SET trigger_tile_id = NULL WHERE trigger_tile_id IS NOT NULL;

-- Also nullify references in events table
DELETE FROM events WHERE tile_id IS NOT NULL;

-- Now clear existing partial tile data
DELETE FROM tiles;

-- Insert all 260 tiles: 4 boards × 64 tiles + 4 FREE integrator tiles
-- LOVE board (IDs 1-64)
INSERT INTO tiles (id, board, calm_magic_phase, row, col, hexagram, tzolkin_index, default_process_state, wu_wei_intensity, senge_discipline, short_prompt, mindfulness_focus) VALUES
(1, 'LOVE', 'LOVE', 1, 1, 1, 1, 'GLITCH', 'HIGH', 'PersonalMastery', 'What risk feels both scary and alive right now?', '["non-judging", "beginners-mind"]'),
(2, 'LOVE', 'LOVE', 1, 2, 2, 2, 'GLITCH', 'HIGH', 'PersonalMastery', 'Where am I withholding care or compassion?', '["non-judging", "trust"]'),
(3, 'LOVE', 'LOVE', 1, 3, 3, 3, 'GLITCH', 'HIGH', 'MentalModels', 'What lens am I using that might be distorting reality?', '["non-judging", "beginners-mind"]'),
(4, 'LOVE', 'LOVE', 1, 4, 4, 4, 'GLITCH', 'HIGH', 'MentalModels', 'What belief is holding me back but feels hard to release?', '["letting-go", "acceptance"]'),
(5, 'LOVE', 'LOVE', 1, 5, 5, 5, 'GLITCH', 'HIGH', 'SharedVision', 'What assumption am I treating as fixed that could be designed?', '["beginners-mind", "non-striving"]'),
(6, 'LOVE', 'LOVE', 1, 6, 6, 6, 'GLITCH', 'HIGH', 'SharedVision', 'What am I trying to force instead of nurture?', '["patience", "trust"]'),
(7, 'LOVE', 'LOVE', 1, 7, 7, 7, 'GLITCH', 'HIGH', 'TeamLearning', 'Where am I performing instead of practicing?', '["non-striving", "acceptance"]'),
(8, 'LOVE', 'LOVE', 1, 8, 8, 8, 'GLITCH', 'HIGH', 'SystemsThinking', 'What larger pattern am I ignoring by focusing too narrowly?', '["non-judging", "beginners-mind"]'),
(9, 'LOVE', 'LOVE', 2, 1, 9, 9, 'GLITCH', 'HIGH', 'PersonalMastery', 'What small experiment am I avoiding?', '["non-striving", "trust"]'),
(10, 'LOVE', 'LOVE', 2, 2, 10, 10, 'GLITCH', 'HIGH', 'PersonalMastery', 'Who needs to feel my care through action right now?', '["non-judging", "trust"]'),
(11, 'LOVE', 'LOVE', 2, 3, 11, 11, 'GLITCH', 'HIGH', 'MentalModels', 'What am I assuming instead of actually observing?', '["beginners-mind", "non-judging"]'),
(12, 'LOVE', 'LOVE', 2, 4, 12, 12, 'GLITCH', 'HIGH', 'MentalModels', 'What habitual response am I stuck in?', '["letting-go", "beginners-mind"]'),
(13, 'LOVE', 'LOVE', 2, 5, 13, 13, 'GLITCH', 'HIGH', 'SharedVision', 'What micro-experience could use a quick redesign?', '["beginners-mind", "non-striving"]'),
(14, 'LOVE', 'LOVE', 2, 6, 14, 14, 'GLITCH', 'HIGH', 'SharedVision', 'What quick seed could I sow in the next hour?', '["patience", "trust"]'),
(15, 'LOVE', 'LOVE', 2, 7, 15, 15, 'GLITCH', 'HIGH', 'TeamLearning', 'What small repeated action would change everything?', '["non-striving", "patience"]'),
(16, 'LOVE', 'LOVE', 2, 8, 16, 16, 'GLITCH', 'HIGH', 'SystemsThinking', 'What agility am I still doing manually that could be encoded?', '["non-judging", "acceptance"]'),
(17, 'LOVE', 'LOVE', 3, 1, 17, 17, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What outcome feels too bold to name?', '["non-striving", "trust"]'),
(18, 'LOVE', 'LOVE', 3, 2, 18, 18, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What would success look like if I centered care over metrics?', '["non-judging", "acceptance"]'),
(19, 'LOVE', 'LOVE', 3, 3, 19, 19, 'GLITCH', 'MEDIUM', 'MentalModels', 'Who am I becoming through this pursuit?', '["beginners-mind", "non-judging"]'),
(20, 'LOVE', 'LOVE', 3, 4, 20, 20, 'GLITCH', 'MEDIUM', 'MentalModels', 'What old pattern needs to die for this to work?', '["letting-go", "acceptance"]'),
(21, 'LOVE', 'LOVE', 3, 5, 21, 21, 'GLITCH', 'MEDIUM', 'SharedVision', 'What experience am I really trying to create?', '["beginners-mind", "trust"]'),
(22, 'LOVE', 'LOVE', 3, 6, 22, 22, 'GLITCH', 'MEDIUM', 'SharedVision', 'What could actually grow from this if I let it?', '["patience", "trust"]'),
(23, 'LOVE', 'LOVE', 3, 7, 23, 23, 'GLITCH', 'MEDIUM', 'TeamLearning', 'What skill do I want to make second nature?', '["non-striving", "patience"]'),
(24, 'LOVE', 'LOVE', 3, 8, 24, 24, 'GLITCH', 'MEDIUM', 'SystemsThinking', 'What should happen automatically without my intervention?', '["non-judging", "trust"]'),
(25, 'LOVE', 'LOVE', 4, 1, 25, 25, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What opportunity am I not seeing because I''m too close?', '["beginners-mind", "non-judging"]'),
(26, 'LOVE', 'LOVE', 4, 2, 26, 26, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'Where is there unexpressed emotion in the system?', '["non-judging", "acceptance"]'),
(27, 'LOVE', 'LOVE', 4, 3, 27, 27, 'DRIFT', 'MEDIUM', 'MentalModels', 'What stories are people telling themselves that shape this landscape?', '["beginners-mind", "non-judging"]'),
(28, 'LOVE', 'LOVE', 4, 4, 28, 28, 'DRIFT', 'MEDIUM', 'MentalModels', 'What just changed that I haven''t fully registered?', '["beginners-mind", "acceptance"]'),
(29, 'LOVE', 'LOVE', 4, 5, 29, 29, 'DRIFT', 'MEDIUM', 'SharedVision', 'What are the pain points in the current journey?', '["non-judging", "acceptance"]'),
(30, 'LOVE', 'LOVE', 4, 6, 30, 30, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where am I planting in rocky soil when fertile ground is nearby?', '["patience", "beginners-mind"]'),
(31, 'LOVE', 'LOVE', 4, 7, 31, 31, 'DRIFT', 'MEDIUM', 'TeamLearning', 'What practices are already working that I could learn from?', '["beginners-mind", "trust"]'),
(32, 'LOVE', 'LOVE', 4, 8, 32, 32, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'What feedback loops are operating here?', '["non-judging", "beginners-mind"]'),
(33, 'LOVE', 'LOVE', 5, 1, 33, 33, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'Am I pushing too hard or playing too safe?', '["non-striving", "acceptance"]'),
(34, 'LOVE', 'LOVE', 5, 2, 34, 34, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotions are fueling this work, for better or worse?', '["non-judging", "acceptance"]'),
(35, 'LOVE', 'LOVE', 5, 3, 35, 35, 'DRIFT', 'MEDIUM', 'MentalModels', 'What am I giving attention to that doesn''t deserve it?', '["non-judging", "letting-go"]'),
(36, 'LOVE', 'LOVE', 5, 4, 36, 36, 'DRIFT', 'MEDIUM', 'MentalModels', 'What should I stop doing to free up energy?', '["letting-go", "acceptance"]'),
(37, 'LOVE', 'LOVE', 5, 5, 37, 37, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where is the experience unnecessarily draining?', '["non-judging", "acceptance"]'),
(38, 'LOVE', 'LOVE', 5, 6, 38, 38, 'DRIFT', 'MEDIUM', 'SharedVision', 'Am I trying to grow too many seeds at once?', '["patience", "non-striving"]'),
(39, 'LOVE', 'LOVE', 5, 7, 39, 39, 'DRIFT', 'MEDIUM', 'TeamLearning', 'Where is rest missing from my practice?', '["non-striving", "acceptance"]'),
(40, 'LOVE', 'LOVE', 5, 8, 40, 40, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'How will the system protect itself from burnout?', '["non-judging", "acceptance"]'),
(41, 'LOVE', 'LOVE', 6, 1, 41, 41, 'DRIFT', 'LOW', 'PersonalMastery', 'What makes experimentation feel unsafe here?', '["non-judging", "trust"]'),
(42, 'LOVE', 'LOVE', 6, 2, 42, 42, 'DRIFT', 'LOW', 'PersonalMastery', 'Whose dignity or vulnerability is at risk?', '["non-judging", "acceptance"]'),
(43, 'LOVE', 'LOVE', 6, 3, 43, 43, 'DRIFT', 'LOW', 'MentalModels', 'What hidden assumptions are our rules based on?', '["beginners-mind", "non-judging"]'),
(44, 'LOVE', 'LOVE', 6, 4, 44, 44, 'DRIFT', 'LOW', 'MentalModels', 'Which rule is outdated but still enforced?', '["letting-go", "beginners-mind"]'),
(45, 'LOVE', 'LOVE', 6, 5, 45, 45, 'DRIFT', 'LOW', 'SharedVision', 'Where is the norm just written, not embedded?', '["non-striving", "trust"]'),
(46, 'LOVE', 'LOVE', 6, 6, 46, 46, 'DRIFT', 'LOW', 'SharedVision', 'What ethical boundaries need explicit naming?', '["non-judging", "acceptance"]'),
(47, 'LOVE', 'LOVE', 6, 7, 47, 47, 'DRIFT', 'LOW', 'TeamLearning', 'What practice-level norms need explicit agreement?', '["trust", "acceptance"]'),
(48, 'LOVE', 'LOVE', 6, 8, 48, 48, 'DRIFT', 'LOW', 'SystemsThinking', 'What norms should be enforced automatically?', '["non-judging", "trust"]'),
(49, 'LOVE', 'LOVE', 7, 1, 49, 49, 'TUNE', 'LOW', 'PersonalMastery', 'What cross-functional synergy am I missing?', '["beginners-mind", "trust"]'),
(50, 'LOVE', 'LOVE', 7, 2, 50, 50, 'TUNE', 'LOW', 'PersonalMastery', 'Where could care compound if connected?', '["non-judging", "trust"]'),
(51, 'LOVE', 'LOVE', 7, 3, 51, 51, 'TUNE', 'LOW', 'MentalModels', 'What shared understanding is missing?', '["beginners-mind", "non-judging"]'),
(52, 'LOVE', 'LOVE', 7, 4, 52, 52, 'TUNE', 'LOW', 'MentalModels', 'What trade-off are we pretending doesn''t exist?', '["non-judging", "acceptance"]'),
(53, 'LOVE', 'LOVE', 7, 5, 53, 53, 'TUNE', 'LOW', 'SharedVision', 'What handoff or transition is currently broken?', '["non-judging", "acceptance"]'),
(54, 'LOVE', 'LOVE', 7, 6, 54, 54, 'TUNE', 'LOW', 'SharedVision', 'How can our seeds cross-pollinate?', '["patience", "trust"]'),
(55, 'LOVE', 'LOVE', 7, 7, 55, 55, 'TUNE', 'LOW', 'TeamLearning', 'What ritual could tie all the practices together?', '["non-striving", "trust"]'),
(56, 'LOVE', 'LOVE', 7, 8, 56, 56, 'TUNE', 'LOW', 'SystemsThinking', 'How could multiple loops reinforce each other?', '["non-judging", "beginners-mind"]'),
(57, 'LOVE', 'LOVE', 8, 1, 57, 57, 'TUNE', 'LOW', 'PersonalMastery', 'What protocol protects innovation from premature shutdown?', '["trust", "non-striving"]'),
(58, 'LOVE', 'LOVE', 8, 2, 58, 58, 'TUNE', 'LOW', 'PersonalMastery', 'What consent protocol is needed?', '["non-judging", "acceptance"]'),
(59, 'LOVE', 'LOVE', 8, 3, 59, 59, 'TUNE', 'LOW', 'MentalModels', 'What is the minimum viable ontology?', '["beginners-mind", "non-judging"]'),
(60, 'LOVE', 'LOVE', 8, 4, 60, 60, 'TUNE', 'LOW', 'MentalModels', 'What pivot/sunset protocol is needed?', '["letting-go", "acceptance"]'),
(61, 'LOVE', 'LOVE', 8, 5, 61, 61, 'TUNE', 'LOW', 'SharedVision', 'What is the interaction blueprint?', '["non-striving", "trust"]'),
(62, 'LOVE', 'LOVE', 8, 6, 62, 62, 'TUNE', 'LOW', 'SharedVision', 'What is the minimal V0.1 pilot kit?', '["patience", "trust"]'),
(63, 'LOVE', 'LOVE', 8, 7, 63, 63, 'TUNE', 'LOW', 'TeamLearning', 'What SOP or reference architecture captures the method?', '["non-striving", "acceptance"]'),
(64, 'LOVE', 'LOVE', 8, 8, 64, 64, 'TUNE', 'LOW', 'SystemsThinking', 'What is the governed system diagram?', '["non-judging", "beginners-mind"]'),
(65, 'MAGIC', 'MAGIC', 1, 1, 1, 65, 'GLITCH', 'HIGH', 'PersonalMastery', 'What creative possibility feels both exciting and uncertain?', '["non-judging", "beginners-mind"]'),
(66, 'MAGIC', 'MAGIC', 1, 2, 2, 66, 'GLITCH', 'HIGH', 'PersonalMastery', 'What story wants to be told through this work?', '["non-judging", "trust"]'),
(67, 'MAGIC', 'MAGIC', 1, 3, 3, 67, 'GLITCH', 'HIGH', 'MentalModels', 'What paradigm shift is trying to happen?', '["non-judging", "beginners-mind"]'),
(68, 'MAGIC', 'MAGIC', 1, 4, 4, 68, 'GLITCH', 'HIGH', 'MentalModels', 'What old story needs to transform?', '["letting-go", "acceptance"]'),
(69, 'MAGIC', 'MAGIC', 1, 5, 5, 69, 'GLITCH', 'HIGH', 'SharedVision', 'What prototype wants to emerge?', '["beginners-mind", "non-striving"]'),
(70, 'MAGIC', 'MAGIC', 1, 6, 6, 70, 'GLITCH', 'HIGH', 'SharedVision', 'What wants to grow naturally if I make space?', '["patience", "trust"]'),
(71, 'MAGIC', 'MAGIC', 1, 7, 7, 71, 'GLITCH', 'HIGH', 'TeamLearning', 'What ritual could unlock creative flow?', '["non-striving", "acceptance"]'),
(72, 'MAGIC', 'MAGIC', 1, 8, 8, 72, 'GLITCH', 'HIGH', 'SystemsThinking', 'What emergent pattern am I not yet seeing?', '["non-judging", "beginners-mind"]'),
(73, 'MAGIC', 'MAGIC', 2, 1, 9, 73, 'GLITCH', 'HIGH', 'PersonalMastery', 'What creative experiment could I try today?', '["non-striving", "trust"]'),
(74, 'MAGIC', 'MAGIC', 2, 2, 10, 74, 'GLITCH', 'HIGH', 'PersonalMastery', 'What heart-led action could spark magic?', '["non-judging", "trust"]'),
(75, 'MAGIC', 'MAGIC', 2, 3, 11, 75, 'GLITCH', 'HIGH', 'MentalModels', 'What would I notice if I looked with fresh eyes?', '["beginners-mind", "non-judging"]'),
(76, 'MAGIC', 'MAGIC', 2, 4, 12, 76, 'GLITCH', 'HIGH', 'MentalModels', 'What would happen if I did the opposite?', '["letting-go", "beginners-mind"]'),
(77, 'MAGIC', 'MAGIC', 2, 5, 13, 77, 'GLITCH', 'HIGH', 'SharedVision', 'What quick prototype could reveal truth?', '["beginners-mind", "non-striving"]'),
(78, 'MAGIC', 'MAGIC', 2, 6, 14, 78, 'GLITCH', 'HIGH', 'SharedVision', 'What seed could I plant in the next hour?', '["patience", "trust"]'),
(79, 'MAGIC', 'MAGIC', 2, 7, 15, 79, 'GLITCH', 'HIGH', 'TeamLearning', 'What practice, repeated daily, would change everything?', '["non-striving", "patience"]'),
(80, 'MAGIC', 'MAGIC', 2, 8, 16, 80, 'GLITCH', 'HIGH', 'SystemsThinking', 'What could be automated to free creative energy?', '["non-judging", "acceptance"]'),
(81, 'MAGIC', 'MAGIC', 3, 1, 17, 81, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What bold outcome could this become?', '["non-striving", "trust"]'),
(82, 'MAGIC', 'MAGIC', 3, 2, 18, 82, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What would success look like through the lens of meaning?', '["non-judging", "acceptance"]'),
(83, 'MAGIC', 'MAGIC', 3, 3, 19, 83, 'GLITCH', 'MEDIUM', 'MentalModels', 'Who are we becoming through this creation?', '["beginners-mind", "non-judging"]'),
(84, 'MAGIC', 'MAGIC', 3, 4, 20, 84, 'GLITCH', 'MEDIUM', 'MentalModels', 'What must transform for the new to emerge?', '["letting-go", "acceptance"]'),
(85, 'MAGIC', 'MAGIC', 3, 5, 21, 85, 'GLITCH', 'MEDIUM', 'SharedVision', 'What diegetic experience must exist?', '["beginners-mind", "trust"]'),
(86, 'MAGIC', 'MAGIC', 3, 6, 22, 86, 'GLITCH', 'MEDIUM', 'SharedVision', 'What could grow from this seed story?', '["patience", "trust"]'),
(87, 'MAGIC', 'MAGIC', 3, 7, 23, 87, 'GLITCH', 'MEDIUM', 'TeamLearning', 'What creative skill wants to develop?', '["non-striving", "patience"]'),
(88, 'MAGIC', 'MAGIC', 3, 8, 24, 88, 'GLITCH', 'MEDIUM', 'SystemsThinking', 'What should emerge naturally from the system?', '["non-judging", "trust"]'),
(89, 'MAGIC', 'MAGIC', 4, 1, 25, 89, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What possibilities exist in the creative landscape?', '["beginners-mind", "non-judging"]'),
(90, 'MAGIC', 'MAGIC', 4, 2, 26, 90, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotions are present in the creative field?', '["non-judging", "acceptance"]'),
(91, 'MAGIC', 'MAGIC', 4, 3, 27, 91, 'DRIFT', 'MEDIUM', 'MentalModels', 'What narratives shape the creative space?', '["beginners-mind", "non-judging"]'),
(92, 'MAGIC', 'MAGIC', 4, 4, 28, 92, 'DRIFT', 'MEDIUM', 'MentalModels', 'What is shifting in the creative terrain?', '["beginners-mind", "acceptance"]'),
(93, 'MAGIC', 'MAGIC', 4, 5, 29, 93, 'DRIFT', 'MEDIUM', 'SharedVision', 'What is the current experience journey?', '["non-judging", "acceptance"]'),
(94, 'MAGIC', 'MAGIC', 4, 6, 30, 94, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where is the most fertile ground for ideas?', '["patience", "beginners-mind"]'),
(95, 'MAGIC', 'MAGIC', 4, 7, 31, 95, 'DRIFT', 'MEDIUM', 'TeamLearning', 'What methods are already working magically?', '["beginners-mind", "trust"]'),
(96, 'MAGIC', 'MAGIC', 4, 8, 32, 96, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'What feedback loops drive creative emergence?', '["non-judging", "beginners-mind"]'),
(97, 'MAGIC', 'MAGIC', 5, 1, 33, 97, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What is my creative energy level right now?', '["non-striving", "acceptance"]'),
(98, 'MAGIC', 'MAGIC', 5, 2, 34, 98, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotions fuel or block creativity?', '["non-judging", "acceptance"]'),
(99, 'MAGIC', 'MAGIC', 5, 3, 35, 99, 'DRIFT', 'MEDIUM', 'MentalModels', 'What deserves my creative attention?', '["non-judging", "letting-go"]'),
(100, 'MAGIC', 'MAGIC', 5, 4, 36, 100, 'DRIFT', 'MEDIUM', 'MentalModels', 'What should I release to free creative energy?', '["letting-go", "acceptance"]'),
(101, 'MAGIC', 'MAGIC', 5, 5, 37, 101, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where does the creative experience drain energy?', '["non-judging", "acceptance"]'),
(102, 'MAGIC', 'MAGIC', 5, 6, 38, 102, 'DRIFT', 'MEDIUM', 'SharedVision', 'How many creative seeds can flourish together?', '["patience", "non-striving"]'),
(103, 'MAGIC', 'MAGIC', 5, 7, 39, 103, 'DRIFT', 'MEDIUM', 'TeamLearning', 'How does rest support creative emergence?', '["non-striving", "acceptance"]'),
(104, 'MAGIC', 'MAGIC', 5, 8, 40, 104, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'How does the creative system sustain itself?', '["non-judging", "acceptance"]'),
(105, 'MAGIC', 'MAGIC', 6, 1, 41, 105, 'DRIFT', 'LOW', 'PersonalMastery', 'What makes creative risk-taking safe?', '["non-judging", "trust"]'),
(106, 'MAGIC', 'MAGIC', 6, 2, 42, 106, 'DRIFT', 'LOW', 'PersonalMastery', 'How do we protect creative vulnerability?', '["non-judging", "acceptance"]'),
(107, 'MAGIC', 'MAGIC', 6, 3, 43, 107, 'DRIFT', 'LOW', 'MentalModels', 'What assumptions shape creative norms?', '["beginners-mind", "non-judging"]'),
(108, 'MAGIC', 'MAGIC', 6, 4, 44, 108, 'DRIFT', 'LOW', 'MentalModels', 'What creative rule needs updating?', '["letting-go", "beginners-mind"]'),
(109, 'MAGIC', 'MAGIC', 6, 5, 45, 109, 'DRIFT', 'LOW', 'SharedVision', 'How can design embody creative principles?', '["non-striving", "trust"]'),
(110, 'MAGIC', 'MAGIC', 6, 6, 46, 110, 'DRIFT', 'LOW', 'SharedVision', 'What ethical boundaries guide creation?', '["non-judging", "acceptance"]'),
(111, 'MAGIC', 'MAGIC', 6, 7, 47, 111, 'DRIFT', 'LOW', 'TeamLearning', 'What creative practice norms need agreement?', '["trust", "acceptance"]'),
(112, 'MAGIC', 'MAGIC', 6, 8, 48, 112, 'DRIFT', 'LOW', 'SystemsThinking', 'What creative norms should be automatic?', '["non-judging", "trust"]'),
(113, 'MAGIC', 'MAGIC', 7, 1, 49, 113, 'TUNE', 'LOW', 'PersonalMastery', 'What creative synergies are possible?', '["beginners-mind", "trust"]'),
(114, 'MAGIC', 'MAGIC', 7, 2, 50, 114, 'TUNE', 'LOW', 'PersonalMastery', 'How could stories compound through connection?', '["non-judging", "trust"]'),
(115, 'MAGIC', 'MAGIC', 7, 3, 51, 115, 'TUNE', 'LOW', 'MentalModels', 'What shared creative understanding is missing?', '["beginners-mind", "non-judging"]'),
(116, 'MAGIC', 'MAGIC', 7, 4, 52, 116, 'TUNE', 'LOW', 'MentalModels', 'What creative tension needs acknowledgment?', '["non-judging", "acceptance"]'),
(117, 'MAGIC', 'MAGIC', 7, 5, 53, 117, 'TUNE', 'LOW', 'SharedVision', 'What creative handoff needs attention?', '["non-judging", "acceptance"]'),
(118, 'MAGIC', 'MAGIC', 7, 6, 54, 118, 'TUNE', 'LOW', 'SharedVision', 'How can creative seeds cross-pollinate?', '["patience", "trust"]'),
(119, 'MAGIC', 'MAGIC', 7, 7, 55, 119, 'TUNE', 'LOW', 'TeamLearning', 'What ritual ties creative practices together?', '["non-striving", "trust"]'),
(120, 'MAGIC', 'MAGIC', 7, 8, 56, 120, 'TUNE', 'LOW', 'SystemsThinking', 'How do creative loops reinforce each other?', '["non-judging", "beginners-mind"]'),
(121, 'MAGIC', 'MAGIC', 8, 1, 57, 121, 'TUNE', 'LOW', 'PersonalMastery', 'What protocol protects creative emergence?', '["trust", "non-striving"]'),
(122, 'MAGIC', 'MAGIC', 8, 2, 58, 122, 'TUNE', 'LOW', 'PersonalMastery', 'What consent protocol supports co-creation?', '["non-judging", "acceptance"]'),
(123, 'MAGIC', 'MAGIC', 8, 3, 59, 123, 'TUNE', 'LOW', 'MentalModels', 'What is the minimum viable storyworld?', '["beginners-mind", "non-judging"]'),
(124, 'MAGIC', 'MAGIC', 8, 4, 60, 124, 'TUNE', 'LOW', 'MentalModels', 'What evolution protocol guides transformation?', '["letting-go", "acceptance"]'),
(125, 'MAGIC', 'MAGIC', 8, 5, 61, 125, 'TUNE', 'LOW', 'SharedVision', 'What is the creative interaction blueprint?', '["non-striving", "trust"]'),
(126, 'MAGIC', 'MAGIC', 8, 6, 62, 126, 'TUNE', 'LOW', 'SharedVision', 'What is the minimum viable creative prototype?', '["patience", "trust"]'),
(127, 'MAGIC', 'MAGIC', 8, 7, 63, 127, 'TUNE', 'LOW', 'TeamLearning', 'What creative method needs documentation?', '["non-striving", "acceptance"]'),
(128, 'MAGIC', 'MAGIC', 8, 8, 64, 128, 'TUNE', 'LOW', 'SystemsThinking', 'What is the creative system architecture?', '["non-judging", "beginners-mind"]'),
(129, 'CALM', 'CALM', 1, 1, 1, 129, 'GLITCH', 'HIGH', 'PersonalMastery', 'What structured approach feels necessary yet uncomfortable?', '["non-judging", "beginners-mind"]'),
(130, 'CALM', 'CALM', 1, 2, 2, 130, 'GLITCH', 'HIGH', 'PersonalMastery', 'Where does compassion meet structure?', '["non-judging", "trust"]'),
(131, 'CALM', 'CALM', 1, 3, 3, 131, 'GLITCH', 'HIGH', 'MentalModels', 'What mental model brings clarity?', '["non-judging", "beginners-mind"]'),
(132, 'CALM', 'CALM', 1, 4, 4, 132, 'GLITCH', 'HIGH', 'MentalModels', 'What needs to be released for clarity to emerge?', '["letting-go", "acceptance"]'),
(133, 'CALM', 'CALM', 1, 5, 5, 133, 'GLITCH', 'HIGH', 'SharedVision', 'What design decision brings order?', '["beginners-mind", "non-striving"]'),
(134, 'CALM', 'CALM', 1, 6, 6, 134, 'GLITCH', 'HIGH', 'SharedVision', 'What wants to stabilize naturally?', '["patience", "trust"]'),
(135, 'CALM', 'CALM', 1, 7, 7, 135, 'GLITCH', 'HIGH', 'TeamLearning', 'What practice brings calm to the work?', '["non-striving", "acceptance"]'),
(136, 'CALM', 'CALM', 1, 8, 8, 136, 'GLITCH', 'HIGH', 'SystemsThinking', 'What systemic pattern brings stability?', '["non-judging", "beginners-mind"]'),
(137, 'CALM', 'CALM', 2, 1, 9, 137, 'GLITCH', 'HIGH', 'PersonalMastery', 'What careful experiment would reduce uncertainty?', '["non-striving", "trust"]'),
(138, 'CALM', 'CALM', 2, 2, 10, 138, 'GLITCH', 'HIGH', 'PersonalMastery', 'How can I act with care and precision?', '["non-judging", "trust"]'),
(139, 'CALM', 'CALM', 2, 3, 11, 139, 'GLITCH', 'HIGH', 'MentalModels', 'What would careful observation reveal?', '["beginners-mind", "non-judging"]'),
(140, 'CALM', 'CALM', 2, 4, 12, 140, 'GLITCH', 'HIGH', 'MentalModels', 'What calm reversal would help?', '["letting-go", "beginners-mind"]'),
(141, 'CALM', 'CALM', 2, 5, 13, 141, 'GLITCH', 'HIGH', 'SharedVision', 'What small redesign would simplify things?', '["beginners-mind", "non-striving"]'),
(142, 'CALM', 'CALM', 2, 6, 14, 142, 'GLITCH', 'HIGH', 'SharedVision', 'What seed needs patient tending?', '["patience", "trust"]'),
(143, 'CALM', 'CALM', 2, 7, 15, 143, 'GLITCH', 'HIGH', 'TeamLearning', 'What daily practice would ground the work?', '["non-striving", "patience"]'),
(144, 'CALM', 'CALM', 2, 8, 16, 144, 'GLITCH', 'HIGH', 'SystemsThinking', 'What could be systematized for calm?', '["non-judging", "acceptance"]'),
(145, 'CALM', 'CALM', 3, 1, 17, 145, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What sustainable outcome feels right?', '["non-striving", "trust"]'),
(146, 'CALM', 'CALM', 3, 2, 18, 146, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What would success look like if stability mattered most?', '["non-judging", "acceptance"]'),
(147, 'CALM', 'CALM', 3, 3, 19, 147, 'GLITCH', 'MEDIUM', 'MentalModels', 'Who are we becoming through this ordering?', '["beginners-mind", "non-judging"]'),
(148, 'CALM', 'CALM', 3, 4, 20, 148, 'GLITCH', 'MEDIUM', 'MentalModels', 'What old chaos needs releasing?', '["letting-go", "acceptance"]'),
(149, 'CALM', 'CALM', 3, 5, 21, 149, 'GLITCH', 'MEDIUM', 'SharedVision', 'What clear experience must exist?', '["beginners-mind", "trust"]'),
(150, 'CALM', 'CALM', 3, 6, 22, 150, 'GLITCH', 'MEDIUM', 'SharedVision', 'What could grow steadily from this foundation?', '["patience", "trust"]'),
(151, 'CALM', 'CALM', 3, 7, 23, 151, 'GLITCH', 'MEDIUM', 'TeamLearning', 'What skill needs steady development?', '["non-striving", "patience"]'),
(152, 'CALM', 'CALM', 3, 8, 24, 152, 'GLITCH', 'MEDIUM', 'SystemsThinking', 'What should run smoothly without attention?', '["non-judging", "trust"]'),
(153, 'CALM', 'CALM', 4, 1, 25, 153, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What opportunities exist in the ordered landscape?', '["beginners-mind", "non-judging"]'),
(154, 'CALM', 'CALM', 4, 2, 26, 154, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotional clarity is present?', '["non-judging", "acceptance"]'),
(155, 'CALM', 'CALM', 4, 3, 27, 155, 'DRIFT', 'MEDIUM', 'MentalModels', 'What clear narratives shape the space?', '["beginners-mind", "non-judging"]'),
(156, 'CALM', 'CALM', 4, 4, 28, 156, 'DRIFT', 'MEDIUM', 'MentalModels', 'What is settling into place?', '["beginners-mind", "acceptance"]'),
(157, 'CALM', 'CALM', 4, 5, 29, 157, 'DRIFT', 'MEDIUM', 'SharedVision', 'What is the clear journey through this space?', '["non-judging", "acceptance"]'),
(158, 'CALM', 'CALM', 4, 6, 30, 158, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where is the most stable ground?', '["patience", "beginners-mind"]'),
(159, 'CALM', 'CALM', 4, 7, 31, 159, 'DRIFT', 'MEDIUM', 'TeamLearning', 'What established methods work well?', '["beginners-mind", "trust"]'),
(160, 'CALM', 'CALM', 4, 8, 32, 160, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'What feedback loops maintain stability?', '["non-judging", "beginners-mind"]'),
(161, 'CALM', 'CALM', 5, 1, 33, 161, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'Is the pace sustainable?', '["non-striving", "acceptance"]'),
(162, 'CALM', 'CALM', 5, 2, 34, 162, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotions support steady work?', '["non-judging", "acceptance"]'),
(163, 'CALM', 'CALM', 5, 3, 35, 163, 'DRIFT', 'MEDIUM', 'MentalModels', 'What deserves sustained attention?', '["non-judging", "letting-go"]'),
(164, 'CALM', 'CALM', 5, 4, 36, 164, 'DRIFT', 'MEDIUM', 'MentalModels', 'What should be let go for sustainability?', '["letting-go", "acceptance"]'),
(165, 'CALM', 'CALM', 5, 5, 37, 165, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where does the experience need smoothing?', '["non-judging", "acceptance"]'),
(166, 'CALM', 'CALM', 5, 6, 38, 166, 'DRIFT', 'MEDIUM', 'SharedVision', 'How many things can be tended sustainably?', '["patience", "non-striving"]'),
(167, 'CALM', 'CALM', 5, 7, 39, 167, 'DRIFT', 'MEDIUM', 'TeamLearning', 'How is rest integrated into practice?', '["non-striving", "acceptance"]'),
(168, 'CALM', 'CALM', 5, 8, 40, 168, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'How does the system maintain itself?', '["non-judging", "acceptance"]'),
(169, 'CALM', 'CALM', 6, 1, 41, 169, 'DRIFT', 'LOW', 'PersonalMastery', 'What norms support safe experimentation?', '["non-judging", "trust"]'),
(170, 'CALM', 'CALM', 6, 2, 42, 170, 'DRIFT', 'LOW', 'PersonalMastery', 'What boundaries protect wellbeing?', '["non-judging", "acceptance"]'),
(171, 'CALM', 'CALM', 6, 3, 43, 171, 'DRIFT', 'LOW', 'MentalModels', 'What assumptions underlie our structures?', '["beginners-mind", "non-judging"]'),
(172, 'CALM', 'CALM', 6, 4, 44, 172, 'DRIFT', 'LOW', 'MentalModels', 'What rule needs calm reconsideration?', '["letting-go", "beginners-mind"]'),
(173, 'CALM', 'CALM', 6, 5, 45, 173, 'DRIFT', 'LOW', 'SharedVision', 'How can the design itself enforce calm?', '["non-striving", "trust"]'),
(174, 'CALM', 'CALM', 6, 6, 46, 174, 'DRIFT', 'LOW', 'SharedVision', 'What ethical standards bring clarity?', '["non-judging", "acceptance"]'),
(175, 'CALM', 'CALM', 6, 7, 47, 175, 'DRIFT', 'LOW', 'TeamLearning', 'What practice agreements support calm?', '["trust", "acceptance"]'),
(176, 'CALM', 'CALM', 6, 8, 48, 176, 'DRIFT', 'LOW', 'SystemsThinking', 'What norms should be automated?', '["non-judging", "trust"]'),
(177, 'CALM', 'CALM', 7, 1, 49, 177, 'TUNE', 'LOW', 'PersonalMastery', 'What synergies create stability?', '["beginners-mind", "trust"]'),
(178, 'CALM', 'CALM', 7, 2, 50, 178, 'TUNE', 'LOW', 'PersonalMastery', 'How could care compound through structure?', '["non-judging", "trust"]'),
(179, 'CALM', 'CALM', 7, 3, 51, 179, 'TUNE', 'LOW', 'MentalModels', 'What shared understanding needs clarifying?', '["beginners-mind", "non-judging"]'),
(180, 'CALM', 'CALM', 7, 4, 52, 180, 'TUNE', 'LOW', 'MentalModels', 'What trade-off needs calm acceptance?', '["non-judging", "acceptance"]'),
(181, 'CALM', 'CALM', 7, 5, 53, 181, 'TUNE', 'LOW', 'SharedVision', 'What handoff needs more clarity?', '["non-judging", "acceptance"]'),
(182, 'CALM', 'CALM', 7, 6, 54, 182, 'TUNE', 'LOW', 'SharedVision', 'How can foundations support growth?', '["patience", "trust"]'),
(183, 'CALM', 'CALM', 7, 7, 55, 183, 'TUNE', 'LOW', 'TeamLearning', 'What ritual creates consistent practice?', '["non-striving", "trust"]'),
(184, 'CALM', 'CALM', 7, 8, 56, 184, 'TUNE', 'LOW', 'SystemsThinking', 'How do stable loops support each other?', '["non-judging", "beginners-mind"]'),
(185, 'CALM', 'CALM', 8, 1, 57, 185, 'TUNE', 'LOW', 'PersonalMastery', 'What protocol ensures safe innovation?', '["trust", "non-striving"]'),
(186, 'CALM', 'CALM', 8, 2, 58, 186, 'TUNE', 'LOW', 'PersonalMastery', 'What consent process brings clarity?', '["non-judging", "acceptance"]'),
(187, 'CALM', 'CALM', 8, 3, 59, 187, 'TUNE', 'LOW', 'MentalModels', 'What is the clear ontological structure?', '["beginners-mind", "non-judging"]'),
(188, 'CALM', 'CALM', 8, 4, 60, 188, 'TUNE', 'LOW', 'MentalModels', 'What transition protocol is needed?', '["letting-go", "acceptance"]'),
(189, 'CALM', 'CALM', 8, 5, 61, 189, 'TUNE', 'LOW', 'SharedVision', 'What is the clear interaction blueprint?', '["non-striving", "trust"]'),
(190, 'CALM', 'CALM', 8, 6, 62, 190, 'TUNE', 'LOW', 'SharedVision', 'What is the minimal stable pilot?', '["patience", "trust"]'),
(191, 'CALM', 'CALM', 8, 7, 63, 191, 'TUNE', 'LOW', 'TeamLearning', 'What method documentation is needed?', '["non-striving", "acceptance"]'),
(192, 'CALM', 'CALM', 8, 8, 64, 192, 'TUNE', 'LOW', 'SystemsThinking', 'What is the stable system architecture?', '["non-judging", "beginners-mind"]'),
(193, 'OPEN', 'OPEN', 1, 1, 1, 193, 'GLITCH', 'HIGH', 'PersonalMastery', 'What possibility feels expansive right now?', '["non-judging", "beginners-mind"]'),
(194, 'OPEN', 'OPEN', 1, 2, 2, 194, 'GLITCH', 'HIGH', 'PersonalMastery', 'How can I open to deeper care?', '["non-judging", "trust"]'),
(195, 'OPEN', 'OPEN', 1, 3, 3, 195, 'GLITCH', 'HIGH', 'MentalModels', 'What perspective shift would open new space?', '["non-judging", "beginners-mind"]'),
(196, 'OPEN', 'OPEN', 1, 4, 4, 196, 'GLITCH', 'HIGH', 'MentalModels', 'What must I release to open further?', '["letting-go", "acceptance"]'),
(197, 'OPEN', 'OPEN', 1, 5, 5, 197, 'GLITCH', 'HIGH', 'SharedVision', 'What design opens new possibilities?', '["beginners-mind", "non-striving"]'),
(198, 'OPEN', 'OPEN', 1, 6, 6, 198, 'GLITCH', 'HIGH', 'SharedVision', 'What wants to emerge if I stay open?', '["patience", "trust"]'),
(199, 'OPEN', 'OPEN', 1, 7, 7, 199, 'GLITCH', 'HIGH', 'TeamLearning', 'What practice opens new territory?', '["non-striving", "acceptance"]'),
(200, 'OPEN', 'OPEN', 1, 8, 8, 200, 'GLITCH', 'HIGH', 'SystemsThinking', 'What systemic opening am I avoiding?', '["non-judging", "beginners-mind"]'),
(201, 'OPEN', 'OPEN', 2, 1, 9, 201, 'GLITCH', 'HIGH', 'PersonalMastery', 'What experiment would expand my range?', '["non-striving", "trust"]'),
(202, 'OPEN', 'OPEN', 2, 2, 10, 202, 'GLITCH', 'HIGH', 'PersonalMastery', 'What heart-led action would open doors?', '["non-judging", "trust"]'),
(203, 'OPEN', 'OPEN', 2, 3, 11, 203, 'GLITCH', 'HIGH', 'MentalModels', 'What would I see with completely fresh eyes?', '["beginners-mind", "non-judging"]'),
(204, 'OPEN', 'OPEN', 2, 4, 12, 204, 'GLITCH', 'HIGH', 'MentalModels', 'What reversal would open new space?', '["letting-go", "beginners-mind"]'),
(205, 'OPEN', 'OPEN', 2, 5, 13, 205, 'GLITCH', 'HIGH', 'SharedVision', 'What quick prototype would test openness?', '["beginners-mind", "non-striving"]'),
(206, 'OPEN', 'OPEN', 2, 6, 14, 206, 'GLITCH', 'HIGH', 'SharedVision', 'What seed needs space to unfold?', '["patience", "trust"]'),
(207, 'OPEN', 'OPEN', 2, 7, 15, 207, 'GLITCH', 'HIGH', 'TeamLearning', 'What practice would expand capacity?', '["non-striving", "patience"]'),
(208, 'OPEN', 'OPEN', 2, 8, 16, 208, 'GLITCH', 'HIGH', 'SystemsThinking', 'What could open the whole system?', '["non-judging", "acceptance"]'),
(209, 'OPEN', 'OPEN', 3, 1, 17, 209, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What expansive goal calls?', '["non-striving", "trust"]'),
(210, 'OPEN', 'OPEN', 3, 2, 18, 210, 'GLITCH', 'MEDIUM', 'PersonalMastery', 'What success would feel genuinely open?', '["non-judging", "acceptance"]'),
(211, 'OPEN', 'OPEN', 3, 3, 19, 211, 'GLITCH', 'MEDIUM', 'MentalModels', 'Who are we becoming through this opening?', '["beginners-mind", "non-judging"]'),
(212, 'OPEN', 'OPEN', 3, 4, 20, 212, 'GLITCH', 'MEDIUM', 'MentalModels', 'What closure would allow opening?', '["letting-go", "acceptance"]'),
(213, 'OPEN', 'OPEN', 3, 5, 21, 213, 'GLITCH', 'MEDIUM', 'SharedVision', 'What open experience must exist?', '["beginners-mind", "trust"]'),
(214, 'OPEN', 'OPEN', 3, 6, 22, 214, 'GLITCH', 'MEDIUM', 'SharedVision', 'What could grow if given room?', '["patience", "trust"]'),
(215, 'OPEN', 'OPEN', 3, 7, 23, 215, 'GLITCH', 'MEDIUM', 'TeamLearning', 'What skill expands openness?', '["non-striving", "patience"]'),
(216, 'OPEN', 'OPEN', 3, 8, 24, 216, 'GLITCH', 'MEDIUM', 'SystemsThinking', 'What should unfold without force?', '["non-judging", "trust"]'),
(217, 'OPEN', 'OPEN', 4, 1, 25, 217, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What opportunities exist in the open field?', '["beginners-mind", "non-judging"]'),
(218, 'OPEN', 'OPEN', 4, 2, 26, 218, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotions arise in openness?', '["non-judging", "acceptance"]'),
(219, 'OPEN', 'OPEN', 4, 3, 27, 219, 'DRIFT', 'MEDIUM', 'MentalModels', 'What narratives constrain openness?', '["beginners-mind", "non-judging"]'),
(220, 'OPEN', 'OPEN', 4, 4, 28, 220, 'DRIFT', 'MEDIUM', 'MentalModels', 'What is opening that I haven''t noticed?', '["beginners-mind", "acceptance"]'),
(221, 'OPEN', 'OPEN', 4, 5, 29, 221, 'DRIFT', 'MEDIUM', 'SharedVision', 'What is the open journey through this space?', '["non-judging", "acceptance"]'),
(222, 'OPEN', 'OPEN', 4, 6, 30, 222, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where is the most spacious ground?', '["patience", "beginners-mind"]'),
(223, 'OPEN', 'OPEN', 4, 7, 31, 223, 'DRIFT', 'MEDIUM', 'TeamLearning', 'What open methods are available?', '["beginners-mind", "trust"]'),
(224, 'OPEN', 'OPEN', 4, 8, 32, 224, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'What loops allow expansion?', '["non-judging", "beginners-mind"]'),
(225, 'OPEN', 'OPEN', 5, 1, 33, 225, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What energy level supports openness?', '["non-striving", "acceptance"]'),
(226, 'OPEN', 'OPEN', 5, 2, 34, 226, 'DRIFT', 'MEDIUM', 'PersonalMastery', 'What emotions support staying open?', '["non-judging", "acceptance"]'),
(227, 'OPEN', 'OPEN', 5, 3, 35, 227, 'DRIFT', 'MEDIUM', 'MentalModels', 'What deserves open attention?', '["non-judging", "letting-go"]'),
(228, 'OPEN', 'OPEN', 5, 4, 36, 228, 'DRIFT', 'MEDIUM', 'MentalModels', 'What should I release to stay open?', '["letting-go", "acceptance"]'),
(229, 'OPEN', 'OPEN', 5, 5, 37, 229, 'DRIFT', 'MEDIUM', 'SharedVision', 'Where does the experience need more space?', '["non-judging", "acceptance"]'),
(230, 'OPEN', 'OPEN', 5, 6, 38, 230, 'DRIFT', 'MEDIUM', 'SharedVision', 'How much can unfold at once?', '["patience", "non-striving"]'),
(231, 'OPEN', 'OPEN', 5, 7, 39, 231, 'DRIFT', 'MEDIUM', 'TeamLearning', 'How does spaciousness support practice?', '["non-striving", "acceptance"]'),
(232, 'OPEN', 'OPEN', 5, 8, 40, 232, 'DRIFT', 'MEDIUM', 'SystemsThinking', 'How does the system stay open?', '["non-judging", "acceptance"]'),
(233, 'OPEN', 'OPEN', 6, 1, 41, 233, 'DRIFT', 'LOW', 'PersonalMastery', 'What norms support openness?', '["non-judging", "trust"]'),
(234, 'OPEN', 'OPEN', 6, 2, 42, 234, 'DRIFT', 'LOW', 'PersonalMastery', 'What boundaries support open exploration?', '["non-judging", "acceptance"]'),
(235, 'OPEN', 'OPEN', 6, 3, 43, 235, 'DRIFT', 'LOW', 'MentalModels', 'What assumptions limit openness?', '["beginners-mind", "non-judging"]'),
(236, 'OPEN', 'OPEN', 6, 4, 44, 236, 'DRIFT', 'LOW', 'MentalModels', 'What closed rule needs opening?', '["letting-go", "beginners-mind"]'),
(237, 'OPEN', 'OPEN', 6, 5, 45, 237, 'DRIFT', 'LOW', 'SharedVision', 'How can design embody openness?', '["non-striving", "trust"]'),
(238, 'OPEN', 'OPEN', 6, 6, 46, 238, 'DRIFT', 'LOW', 'SharedVision', 'What ethical principles keep doors open?', '["non-judging", "acceptance"]'),
(239, 'OPEN', 'OPEN', 6, 7, 47, 239, 'DRIFT', 'LOW', 'TeamLearning', 'What practice agreements encourage openness?', '["trust", "acceptance"]'),
(240, 'OPEN', 'OPEN', 6, 8, 48, 240, 'DRIFT', 'LOW', 'SystemsThinking', 'What norms keep the system open?', '["non-judging", "trust"]'),
(241, 'OPEN', 'OPEN', 7, 1, 49, 241, 'TUNE', 'LOW', 'PersonalMastery', 'What synergies open new territory?', '["beginners-mind", "trust"]'),
(242, 'OPEN', 'OPEN', 7, 2, 50, 242, 'TUNE', 'LOW', 'PersonalMastery', 'How could openness compound?', '["non-judging", "trust"]'),
(243, 'OPEN', 'OPEN', 7, 3, 51, 243, 'TUNE', 'LOW', 'MentalModels', 'What shared understanding expands?', '["beginners-mind", "non-judging"]'),
(244, 'OPEN', 'OPEN', 7, 4, 52, 244, 'TUNE', 'LOW', 'MentalModels', 'What tension resolves through opening?', '["non-judging", "acceptance"]'),
(245, 'OPEN', 'OPEN', 7, 5, 53, 245, 'TUNE', 'LOW', 'SharedVision', 'What handoff needs more space?', '["non-judging", "acceptance"]'),
(246, 'OPEN', 'OPEN', 7, 6, 54, 246, 'TUNE', 'LOW', 'SharedVision', 'How can seeds share space?', '["patience", "trust"]'),
(247, 'OPEN', 'OPEN', 7, 7, 55, 247, 'TUNE', 'LOW', 'TeamLearning', 'What ritual expands practice?', '["non-striving", "trust"]'),
(248, 'OPEN', 'OPEN', 7, 8, 56, 248, 'TUNE', 'LOW', 'SystemsThinking', 'How do loops keep expanding?', '["non-judging", "beginners-mind"]'),
(249, 'OPEN', 'OPEN', 8, 1, 57, 249, 'TUNE', 'LOW', 'PersonalMastery', 'What protocol keeps innovation open?', '["trust", "non-striving"]'),
(250, 'OPEN', 'OPEN', 8, 2, 58, 250, 'TUNE', 'LOW', 'PersonalMastery', 'What consent process stays open?', '["non-judging", "acceptance"]'),
(251, 'OPEN', 'OPEN', 8, 3, 59, 251, 'TUNE', 'LOW', 'MentalModels', 'What is the open ontology?', '["beginners-mind", "non-judging"]'),
(252, 'OPEN', 'OPEN', 8, 4, 60, 252, 'TUNE', 'LOW', 'MentalModels', 'What evolution keeps things open?', '["letting-go", "acceptance"]'),
(253, 'OPEN', 'OPEN', 8, 5, 61, 253, 'TUNE', 'LOW', 'SharedVision', 'What is the open interaction blueprint?', '["non-striving", "trust"]'),
(254, 'OPEN', 'OPEN', 8, 6, 62, 254, 'TUNE', 'LOW', 'SharedVision', 'What is the minimal open pilot?', '["patience", "trust"]'),
(255, 'OPEN', 'OPEN', 8, 7, 63, 255, 'TUNE', 'LOW', 'TeamLearning', 'What open method needs documentation?', '["non-striving", "acceptance"]'),
(256, 'OPEN', 'OPEN', 8, 8, 64, 256, 'TUNE', 'LOW', 'SystemsThinking', 'What is the open system architecture?', '["non-judging", "beginners-mind"]'),
(257, 'FREE', 'FREE', 1, 1, 1, 257, 'FREE', 'LOW', 'SystemsThinking', 'How does this cycle integrate with previous cycles?', '["non-judging", "trust", "acceptance"]'),
(258, 'FREE', 'FREE', 1, 8, 8, 258, 'FREE', 'LOW', 'SystemsThinking', 'What systemic learning emerged from this journey?', '["beginners-mind", "non-judging", "trust"]'),
(259, 'FREE', 'FREE', 8, 1, 57, 259, 'FREE', 'LOW', 'SystemsThinking', 'What protocols will carry forward?', '["non-striving", "trust", "acceptance"]'),
(260, 'FREE', 'FREE', 8, 8, 64, 260, 'FREE', 'LOW', 'SystemsThinking', 'What is ready to be released into the world?', '["letting-go", "trust", "acceptance"]');