
INSERT INTO public.book_sources (chapter_id, kind, ref, title, excerpt, weight, included) VALUES
('cc2d2c02-5769-4448-9d54-2bc2a1bae1ae','upload','pdf:cm-official#p4-preface-i-think-about-thinking','Préface — "Je réfléchis à réfléchir"','J''ai passé la plus grande partie de ma vie à chercher des explications sur tout ce que je ressentais de l''univers qui m''entourait. Sur tout. Avidement. Un jour, j''ai décidé d''écrire un livre. J''ai amassé tous mes cahiers de notes, mes dessins, mes scripts, ceux des autres, des réflexions jetées sur des bouts de papiers, de cartons de restaurant et j''ai amassé des tas de livres autour de moi. Puis. J''ai réfléchi et réalisé plusieurs projets mais je n''ai pas encore commencé à écrire le livre mais j''ai tout le matériel pour en écrire 5. The book begins where the author begins — in friction with his own abundance, refusing to write until he knew what to transmit.',5,true),
('cc2d2c02-5769-4448-9d54-2bc2a1bae1ae','upload','pdf:cm-official#p1-censoring-system','The Built-in Censoring System','Everyone has a built-in censoring system in their brains that filters thoughts, images, memories and stimuli from the outside world before they reach conscious awareness. Our censoring system keeps us focused on current goals and on information that prior learning has taught us is "appropriate." Learning to loosen up this mental filtering system to allow more novel ideas and stimuli into conscious awareness is one of the biggest challenges for people who don''t think of themselves as creative. The GLITCH is precisely the moment this filter cracks.',5,true),
('cc2d2c02-5769-4448-9d54-2bc2a1bae1ae','upload','pdf:cm-official#p7-current-questionings','Mes questionnements actuels','The book opens with the author''s own live questions about the 21st century: what does it mean to think, learn, see and do differently when the Web becomes the Industrial Internet of Things, when the world becomes programmable, when computing becomes spatial? Friction precedes framework.',5,true),
('cc2d2c02-5769-4448-9d54-2bc2a1bae1ae','upload','pdf:cm-official#p10-ethics-engagement','Ethics & Engagement at Work — Self-Determination Theory','Engaging people at work — Deci & Ryan, Self-Determination Theory (1971-2017, jarche.com). The chapter holds the tension between autonomy, competence and relatedness, and the reality of disengaged workplaces. Engagement lives at the intersection of all three; everything else is friction the organization refuses to name.',5,true),

('33fb756b-fb4f-44ec-a22e-5b99c7f100d5','upload','pdf:cm-official#p5-poiesis-at-the-office','Poiesis at the Office','Poiesis (Ancient Greek ποίησις) is "the activity in which a person brings something into being that did not exist before." I am an Organizational Poet and Experience Architect. I develop the faculty for poiesis in people — new ways of thinking, learning, seeing and doing. After 25 years of practice I have developed Workshops & Learning Expeditions for Creative Leadership, Spatial Computing, Interaction Design, Visual Sensemaking and Storytelling, approached with the eyes of a relational artist.',5,true),
('33fb756b-fb4f-44ec-a22e-5b99c7f100d5','upload','pdf:cm-official#p5-part1-compasses','Part 1 — The Compasses','An ensemble of visual maps exposing various bodies of knowledge and decision-making skills required to thrive with imagination in the 21st century. The Compasses are not maps of territory — they are maps of attention.',5,true),
('33fb756b-fb4f-44ec-a22e-5b99c7f100d5','upload','pdf:cm-official#p9-futurogram','Futurogram — From the Web to Industrial Internet of Things','The Futurogram traces the migration from the Web to the Industrial Internet of Things, the rise of the Programmable World, and the question of how to imagine the impact of Spatial Computing. Drift is the discipline of staying with these signals long enough for patterns to surface.',5,true),
('33fb756b-fb4f-44ec-a22e-5b99c7f100d5','upload','pdf:cm-official#p6-jonathan-parcours','Qui suis-je et quel est mon parcours','Jonathan Bélisle — visionnaire, conférencier, poète d''interactions et transformateur d''entreprises, ambassadeur depuis 22+ ans d''une informatique plus calme, affective, humaniste et multisensorielle. Narratologie au cinéma, pensée visuelle, ethnographie, design de services — fusionnés pour aborder de manière ludique les problèmes complexes : univers narratifs, réalités mixtes, domotique, installations immersives, créativité organisationnelle, IoT, médias en réseaux. Fondateur de Hello, Architekt!, créateur de Wuxia le renard, chercheur au Annenberg Innovation Lab (USC), co-inventeur de iotheatre.co, fondateur de l''initiative NOEM, développeur de la plateforme de récits tangibles CALM.',5,true),

('cd9f5268-7b54-48c3-8a89-8ab80bb966e5','upload','pdf:cm-official#p15-small-framework','The SMALL Framework (2007 origin)','In 2007 the method was called SMALL — Seeds, Maps, Agendas, Lens, Love. The acronym''s components began to combinate from there. SMALL was the seed of CALM MAGIC: the moment the author stopped treating creative leadership as a personality trait and started treating it as a tunable practice. TUNE begins where SMALL begins — with the decision to name the method.',5,true),
('cd9f5268-7b54-48c3-8a89-8ab80bb966e5','upload','pdf:cm-official#p2-agendas','AGENDAS — Set things in motion','AGENDAS is the CALM component that sets things in motion: Analysis · Guidelines · Elaboration · Normalisation · Development · Adaptation · Secrets. It is the operational tuning stage where intention becomes scheduled, scheduled becomes shared, and shared becomes adaptive. AGENDAS is how a creative organization commits without freezing.',5,true),
('cd9f5268-7b54-48c3-8a89-8ab80bb966e5','upload','pdf:cm-official#p24-reinventing-meetings','Reinventing Meetings / Meetings as Encounters','Meetings reframed as encounters: Inspire → Play → Model → Execute, oscillating between Divergence, Exploration and Convergence. The TUNE chapter argues that organizational tempo lives or dies in the meeting — and that most meetings are detuned by default.',5,true),
('cd9f5268-7b54-48c3-8a89-8ab80bb966e5','upload','pdf:cm-official#p17-five-methods','The 5 Methods','What are the images that come to mind for each main story? What visual small details represent each chapter? Story 1: SEEDS. The 5 Methods are the tuned instruments of the framework — each with its own register, its own time signature, its own ear.',5,true),

('c265a00e-4ff3-435d-adc7-18ae3bbfde5f','upload','pdf:cm-official#p2-love-acronym','LOVE — Finding purpose in the small things','LOVE is the CALM component for finding purpose in the small things: Longevity · Oscillations / Directions & Orbits · Velocity · Empathy / Emotional Intelligence. LOVE is not sentiment — it is the load-bearing relational infrastructure of any creative organization that wants to last.',5,true),
('c265a00e-4ff3-435d-adc7-18ae3bbfde5f','upload','pdf:cm-official#p12-relational-artist','The Relational Artist','Part 2 — The Transformers opens with the Relational Artist: the practitioner whose primary medium is the quality of relation between people, between people and tools, between people and futures. Before product, before strategy, before stack — relation.',5,true),
('c265a00e-4ff3-435d-adc7-18ae3bbfde5f','upload','pdf:cm-official#p20-social-good','Social good, cause before result','Je suis davantage dans le social good : la cause plus que le résultat. Je cherche les talents avant le client : le qui en 1er et ensuite le quoi. Je veux donner du sens au monde par le choix de mes projets. LOVE chooses the who before the what.',5,true),
('c265a00e-4ff3-435d-adc7-18ae3bbfde5f','upload','pdf:cm-official#p10-sdt-engagement','Self-Determination Theory at Work','Engaging people at work through Deci & Ryan''s Self-Determination Theory: autonomy, competence and relatedness as the three nutrients of intrinsic motivation. The intersection of all three is engagement; missing any one collapses into disengagement. LOVE is the chapter that takes this seriously as a design constraint.',5,true),

('64b3e0b1-c077-4889-a5de-ac88426abb5d','upload','pdf:cm-official#p2-magic-acronym','MAGIC — Areas of impact','MAGIC is the acronym for the areas of impact of the method: Mindsets · Agility · Goals / Governance / Gardens · Intuition · Cycles / Capabilities / Compasses / Circles. MAGIC is the worldbuilding layer — the diegetic prototype of the organization the team wants to inhabit.',5,true),
('64b3e0b1-c077-4889-a5de-ac88426abb5d','upload','pdf:cm-official#p2-flow-states-tarot','The Flow States Tarot — Major Arcanas','The Flow States Tarot is the secret ingredient that gels the 4 elements — the Major Arcanas of the method. It carries the imaginal register the rest of the framework needs in order to stay alive. Without the tarot, CALM hardens into process; with it, MAGIC stays a practice.',5,true),
('64b3e0b1-c077-4889-a5de-ac88426abb5d','upload','pdf:cm-official#p13-organizational-poet','The Organizational Poet — Organizational Design is Poetry','Organizational Design is Poetry. The Organizational Poet works with metaphor, ritual, naming, tempo, repetition, silence — the same materials a poet uses — but applied to the architecture of an enterprise. The role is not decorative; it is structural.',5,true),
('64b3e0b1-c077-4889-a5de-ac88426abb5d','upload','pdf:cm-official#p27-story-driven','Story-Driven Enterprise Transformation','L''entreprise est un réseau. Comment les histoires se transportent et se transforment dans un réseau. L''importance du StoryTime : réinventer les meetings, les présentations, et installer des rituels d''écoute, de récitation et de création de récits. Storytelling au cœur du développement produit — design d''interactions, design de produits/services, modélisation des processus d''affaires.',5,true),

('fe83ade0-d08b-4cd1-a610-9fb6c3c4745b','upload','pdf:cm-official#p13-calm-framework','The CALM Magic Framework','CALM is the acronym for all the components of the method. Each component''s name represents a stage of the creative leader experience and exposes the process steps. The framework is recursive: CALM names the stages, MAGIC names the impacts, and the Flow States Tarot gels them.',5,true),
('fe83ade0-d08b-4cd1-a610-9fb6c3c4745b','upload','pdf:cm-official#p2-creeds','CREEDS — what simple things are made of','CREEDS is the first CALM component: Chances (Sparks) · Reversal (Inversion) · Envisioning · Exploring & Modeling · Design (playgrounds) · Strategic Structure. CREEDS is the ontology of the small — the unit elements every CALM organization assembles into systems.',5,true),
('fe83ade0-d08b-4cd1-a610-9fb6c3c4745b','upload','pdf:cm-official#p2-lens','LENS — Looking at things from a new perspective','LENS is the CALM component for re-perceiving: Landscapes · Energies · Norms · Synergies. LENS is how a calm organization continually refreshes its angle of attack without burning the team out on novelty.',5,true),
('fe83ade0-d08b-4cd1-a610-9fb6c3c4745b','upload','pdf:cm-official#p2-maps','MAPS — Communicating new things','MAPS is the CALM component for communicating the new: Methods · Architectures · Protocols · Systems. MAPS is the calm scaffolding that lets fast agents — human or otherwise — operate without breaking the team that maintains them.',5,true),
('fe83ade0-d08b-4cd1-a610-9fb6c3c4745b','upload','pdf:cm-official#p23-why-poetry-works','Why Organizational Poetry Works','Ideation techniques that help your teams navigate the unknown and embrace transformation. Usage gives meaning. Create new experiences using tools and methods to communicate the new in your organization — new ways of seeing, thinking, learning and doing. Poetry works because it changes what a team is able to perceive together.',5,true),
('fe83ade0-d08b-4cd1-a610-9fb6c3c4745b','upload','pdf:cm-official#p22-learning-organization','Creative Leadership in the Learning Organization','Learning Organizations need organizational poets and enterprise transformers. Types of creativity required: clarifiers + ideators + developers + implementers = breakthrough. The Learning Organization is where poiesis and praxis stop being separated.',5,true),

('38605e72-e373-4c08-bc49-a5098c489d99','upload','pdf:cm-official#p25-creative-expeditions','Creative / Transition Design Expeditions','I organize Learning Expeditions for any enterprise wishing to transition towards a learning organization model. Expeditions cover Prospective Storytelling, Narratives as Innovation, the Experiential Spectrum of Tangible Interactions, Space/Spatiality, Representations & Expressiveness, Embodied Interactions/Facilitation, Tangible Manipulation, Human Condition Improvement, Applicative Design (UX/IxD/IA/UI Planning), Creative Direction, and Narrative Design & Scenography. FREE is the chapter where the framework dissolves into expedition.',5,true),
('38605e72-e373-4c08-bc49-a5098c489d99','upload','pdf:cm-official#p14-idea-experience-architect','The Idea & Experience Architect','The third Transformer. Where the Relational Artist tends relation and the Organizational Poet shapes form, the Idea & Experience Architect ships — translating poiesis into experiences people actually live through, products people actually use, futures people actually inhabit.',5,true),
('38605e72-e373-4c08-bc49-a5098c489d99','upload','pdf:cm-official#p29-activity-maps','Activity Maps','The closing appendix: Activity Maps. The framework''s final gesture is not a manifesto but a set of maps — concrete activities a team can run on Monday morning. FREE is preferable futures shipped weekly.',5,true),
('38605e72-e373-4c08-bc49-a5098c489d99','upload','pdf:cm-official#p5-preferable-futures','Preferable Futures — bringing innovation to society','Part of my role is to bring innovation to society and start new dialogues around usages of technologies that can build a preferable future. I work with companies, institutions, organizations, schools, museums and cities that want to integrate an Educational & Transformational Design practice in their culture. FREE is the chapter where that practice becomes ordinary.',5,true);

UPDATE public.book_chapters SET summary = 'Why the future arrives as a glitch first. The censoring system, the unwritten book, the questionings of a 21st century mind. Friction precedes framework.' WHERE phase = 'GLITCH';
UPDATE public.book_chapters SET summary = 'The Compasses. Poiesis at the office, the Futurogram, the migration from Web to Industrial IoT to Programmable World to Spatial Computing. Mapping signals before committing.' WHERE phase = 'DRIFT';
UPDATE public.book_chapters SET summary = 'From SMALL (2007) to CALM MAGIC (2023). AGENDAS as the operational tuning of intention. Meetings reinvented as encounters. The 5 Methods.' WHERE phase = 'TUNE';
UPDATE public.book_chapters SET summary = 'LOVE — Longevity, Oscillations, Velocity, Empathy. The Relational Artist. Self-Determination Theory as a design constraint. Choosing the who before the what.' WHERE phase = 'LOVE';
UPDATE public.book_chapters SET summary = 'MAGIC — Mindsets, Agility, Goals/Governance/Gardens, Intuition, Cycles. The Organizational Poet. The Flow States Tarot. Story-Driven Enterprise Transformation.' WHERE phase = 'MAGIC';
UPDATE public.book_chapters SET summary = 'The CALM framework — CREEDS, LENS, AGENDAS, MAPS, LOVE. Why organizational poetry works. Creative leadership in the Learning Organization.' WHERE phase = 'CALM';
UPDATE public.book_chapters SET summary = 'The framework dissolved into practice. Creative/Transition Design Expeditions. The Idea & Experience Architect. Activity Maps. Preferable futures shipped weekly.' WHERE phase = 'FREE';
