
INSERT INTO public.book_sources (chapter_id, kind, title, ref, excerpt, included, weight, notes)
SELECT c.id, 'upload', s.title, s.ref, s.excerpt, true, 2, 'jbelisle-archive 2013-2018'
FROM (VALUES
  ('CALM', 'The #Small Thinking Framework (2013)', 'archive://small-thinking-framework',
   'Hand-drawn meta-framework by Jonathan Bélisle (2013). Central nucleus: TECHNOLOGIES, BEHAVIORS, ECONOMIES, MARKETS, CULTURE, TEKHNÉ. Surrounded by two living layers — ECOLOGIES and INTELLIGENCES — which connect outward to four operational reservoirs: DIALOGUES, KNOWLEDGE BASES, PRACTICES, TOOLS. Read as a Calm Magic primitive: the system is not designed top-down; it emerges from how dialogues, knowledge bases, practices and tools recirculate through living ecologies and intelligences around a stable cultural/technological nucleus. This is the earliest articulation of what later becomes the Calm Magic board: a system that stays calm because every component has a reciprocal counterpart and nothing is freestanding.'),
  ('MAGIC', 'Applied Poetry — Calmer Futures (2016)', 'archive://applied-poetry',
   'Sketch by Jonathan Bélisle (2016) titled "Promoting a calmer future without helmets and less screens". Vocabulary clusters: Tangible Computing, Interaction Design, Sensor Fusion, Calm Computing, Programmable Environment; AI / Machine Learning / Deep Learning / Neural Network; Applied Poetry, Natural Interfaces, Neural Interfaces, Voice Interface, Scenography; Body, Emotions, Geography; Mixed Realities (VR/AR/Whatever), Reduced/Augmented, Assistive/Immersive; Narrative, Meaningful Cognitive Time, More Unstructured Time; Feel, Haptics, Multisensory Experiences — explicitly Not Ocularcentric (the visual cortex takes all our limited attention). This is the source of the Calm Magic stance: imagination is not decoration, it is the engineering discipline that frees attention from screens and gives cognitive time back to the body, to place, and to relationship.'),
  ('DRIFT', 'SMPL (FR) — Imagination Dialogique & Pensée Systémique', 'archive://smpl-fr',
   'Diagramme bilingue de Jonathan Bélisle. Quatre questions de cadrage récurrentes : « Qu''est-ce qui a besoin d''espace pour grandir ? Que sommes-nous en train d''apprendre ? Qu''avons-nous accompli ? Que sommes-nous en train d''imaginer ? » Deux axes : IMAGINATION DIALOGIQUE × PENSÉE SYSTÉMIQUE. Quatre quadrants opératoires : INSPIRER (idéation & médiation), RACONTER (créer du sens), EXÉCUTER (vision & logistique), INVESTIGATION & DÉTECTION. Triptyque méthodologique : OUTILS ↔ MÉTHODES ↔ PROCESSUS, puis CONCEPTS ↔ ARTEFACTS ↔ PROTOTYPES ↔ EXPÉRIENCES. Cycle de divergence → exploration → convergence : suspension consentie de l''incrédulité, favoriser les itérations, créer des opportunités, envisager avec plus de clarté, prendre des chemins inattendus, plonger dans la longue traîne, exécuter avec plus d''agilité, expérience connectée. Source canonique du chapitre Drift : le pattern-exploration est dialogique et systémique en même temps.'),
  ('MAGIC', 'Concentric Methodologies (Story Design)', 'archive://concentric-methodologies',
   'Diagramme à cercles concentriques de Jonathan Bélisle. Couches reliées : Pensée systémique, Design de services, Ethnographie appliquée, Architecture d''expériences (scénarisation de l''expérience utilisateur), Sensemaking (pensée visuelle / facilitation graphique), Idéation & GameStorming, Épiphanie, Modélisation conceptuelle, Story Making (fascination / inspiration / apprentissage et techniques), Prototypage rapide, Poésie appliquée, Design d''interactions, Innovation, Poiesis, Praxis, Story Design (design d''information / structure de récit), Computational Design (génératif / procédural / visualisations / data models). Cette carte est la généalogie complète du « MAGIC » dans Calm Magic : l''imagination pragmatique se pratique à travers une chaîne précise — sentir (ethnographie), faire-sens (sensemaking), incarner (story making), prototyper, et computer.'),
  ('CALM', 'Design Thinking × Service Design × System Architecture Workflow', 'archive://workflow-3-bands',
   'Diagramme manuscrit de Jonathan Bélisle illustrant trois bandes horizontales — Design Thinking, Service Design, System Architecture — reliées par un rituel central : Daily Scrum, Retro (2 semaines), Backlog. À gauche : une « Idée » qui se transforme en activity map et en snippets de code. À droite : Pitching, Problem-Solving, Storytelling, Journey Mapping, puis composants de Release : UI/Canvas, Database, API''s/SaaS. Source du chapitre CALM : « designing the system » signifie tenir simultanément les trois bandes (sens → service → infrastructure) au même rythme de cadence, sans en sacrifier aucune.'),
  ('OPEN', 'Futures Cone — Possibles, Plausibles, Probables, Préférables', 'archive://futures-cone',
   'Illustration classique du cône des futurs adaptée par Jonathan Bélisle : une main tenant une lampe de poche dont les faisceaux projettent quatre cônes successifs depuis le PRÉSENT vers le TEMPS — Futurs possibles ⊃ Futurs plausibles ⊃ Futurs probables ⊃ Futurs préférables. Le chapitre OPEN (Living the Ontology) s''appuie directement sur ce schéma : vivre l''ontologie, c''est refuser d''hériter passivement du futur le plus probable et organiser la pratique pour habiter activement le cône des futurs préférables. La velocity = speed + direction du board Calm Magic est l''opérationalisation de ce cône.'),
  ('OPEN', 'Architecture d''expériences (slide 11) — structure circulaire', 'archive://architecture-experiences-11',
   'Extrait de la conférence « Architecture d''expériences et design des environnements du futur » de Jonathan Bélisle. Diagramme circulaire complexe articulant flux noétiques (mythologies, cosmologies, religions, cultures, écosystèmes), flux perma (objets physiques, dialogues, design narratif, design de démarche, données, espaces virtuels, capteurs, systèmes d''immersion, algorithmes / IA) et courants de fond bio/psy/géo (écologie, biologie, psychologie). Source pour OPEN : l''ontologie vivante est multicouche — il n''y a pas de « système » sans flux noétique au-dessus et courant de fond bio-psy-géo en-dessous.'),
  ('FREE', 'Pistes d''interactions — Capteurs & Environnement programmable', 'archive://pistes-interactions-23',
   'Inventaire opérationnel par Jonathan Bélisle. Capteurs : proximity sensor + weight sensor ; camera vision (position précise, occupation spatiale dans le temps, dynamique de groupe) ; movement detector (vitesse + directionnalité) ; duration of interaction ; weather data ; gyroscope (orientation précise d''objet) ; date & time (mode saisonnier) ; wind detector (force + direction). Signaux : sonography / singularities — substitutions visuelles ou signaux sonores, signal lumineux, impression au sol / sur device / projection au sol, signal de base. Mobile URL : contrôle web pour opérations, modes spéciaux pour événements. Source FREE (Operating in Flow) : le flow opérationnel n''est pas une métaphore — c''est un catalogue concret de capteurs, signaux et modes d''interaction qui rend l''environnement programmable sans le rendre intrusif.'),
  ('LOVE', 'Noétique, Proxémie, Poésie & Neuroleadership', 'archive://noetique-proxemie',
   'Carte conceptuelle de Jonathan Bélisle reliant : GESTION DU CHANGEMENT, NOÉTIQUE, PROXÉMIE (distance personnelle), VOIX INTÉRIEURE (deep selves), PRAXIS, POIESIS, NEUROLEADERSHIP, POÉSIE, SÉRENDIPITÉ, PRISE DE DÉCISION, COLLABORATION, RÉSOLUTION DE PROBLÈME. Trois axes relationnels : GUIDER ↔ DIALOGUE, TOUCH PLAY ↔ LISTEN PLAY, DIRIGER ↔ PENSER LE MONDE. Socle : intelligence relationnelle, intuition, communications non-verbales, empathie. Source LOVE (Relational Infrastructure) : l''infrastructure relationnelle n''est pas un soft-skill — c''est une discipline noétique avec sa propre proxémie, sa praxis et sa poiesis, et c''est elle qui rend possible le neuroleadership et la sérendipité.'),
  ('GLITCH', 'Noetical Flux / Perma Flux / Bio-Psy-Géo Flux', 'archive://noetical-perma-bio-flux',
   'Stratification de Jonathan Bélisle : (1) NOETICAL FLUX — mythologies et cosmologies, religions et cultures, écosystèmes. (2) PERMA FLUX — objets physiques, dialogues, design narratif, design de démarche, données, espaces virtuels, capteurs, systèmes d''immersion, algorithmes / intelligences artificielles. Triades transversales : COMPORTEMENTS ↔ HISTOIRES ↔ MARCHÉS ; TEKHNÉ ↔ PLATEFORMES ↔ TECHNOLOGIES ; ÉCONOMIE ↔ CONTEXTES SOCIOLOGIQUES ↔ GÉOPOLITIQUE. (3) BIO/PSY/GÉO FLUX — courants de fond : écologie, biologie, psychologie. Source GLITCH (Naming the Friction) : un glitch n''est jamais isolé — il faut le nommer simultanément dans son flux noétique, son flux perma et son courant de fond bio-psy-géo, sinon on traite un symptôme et pas une friction structurelle.')
) AS s(phase, title, ref, excerpt)
JOIN public.book_chapters c ON c.phase = s.phase
WHERE NOT EXISTS (
  SELECT 1 FROM public.book_sources bs WHERE bs.chapter_id = c.id AND bs.ref = s.ref
);
