// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeqfbywgcokyxvubjlhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcWZieXdnY29reXh2dWJqbGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDcyMDMsImV4cCI6MjA2MDkyMzIwM30.vzH2QMinJGfOLG0XAMEsEi-xdJh2coTMXVdgE3v0e7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});